### ISSUE TITLE
Question: Relevance of this package?

### ISSUE THREAD

**Issue by Potherca** [gossi/composer-localdev-plugin#4]
I could be mistaken, but doesn't the [Composer Path Repository](https://getcomposer.org/doc/05-repositories.md#path) fix the problem this plugin is trying to address?

References:
- https://github.com/composer/composer/blob/master/src/Composer/Repository/PathRepository.php#L27
- https://github.com/composer/composer/blob/master/src/Composer/Downloader/PathDownloader.php#L53
- https://github.com/composer/composer/pull/4365

**Comment by gossi** [comment]
Yes and no.

Disclaimer: I had this idea before I know about the path repository and started this plugin prior to that - mainly as a research project.

Yet, the path repo have a problem: You configure the paths in your project's composer.json which is pretty bad, especially since you share your project with others, because they need to have the same file layout as you do. My idea is to have them globally configured (`~/composer/config.json`) - as this is already done with this plugin. 

Also Jordi pointed me to path repos and I tried to use path repos with this plugin by reading my global config and adding them as path repo on-the-fly, whenever an update/install is happening but that didn't worked out (may also be a programming mistake by me).

Third: I realized, that sometimes you want to have a symlink and another time you want to have a special version of your dependency (even if it is locally available). So that's also part of this plugin to find out, what would be the best place (#3) to tell composer to use local or deployed version.

At best, the functionality of this plugin will be merged into composer.

**Comment by Potherca** [comment]
Closing, as the question has been answered.

**Comment by mfrieling** [comment]
I still see a relevance of this package, because the _Path repository_ in my opinion can be only a part of the solution. Let me explain with an example.

I'm working on the development setup of a Drupal 8 distribution architecture which contains of basically two distributions as our organization has two very different kind of Drupal sites, lets say for internal and external purposes. External purposes are more or less extended "websites" and internal purposes has many intranet-like features. Our organization has three different levels of operation: international, national and local. All three levels will use external distribution and at least international and national level internal distribution for different, but similar goals.
Resulting we will have a bunch of Drupal modules providing functionality for both distributions as well as some which are only revelant for one. The latter one could be handled without Composer by putting them directly into the distribution Git repo. So lets focus on the shared modules. They are under constant development and not all functionality can be tested isolated using unit tests and similar, as they often only provide API logic etc. So I need to test them together with their consuming modules which either live in own Git repos managed by Composer or in the distro repo. Obviously I don't want to have local/development related stuff in Git.

Thus the _Path repository_ helps me putting the packages under development on my local machine and develop and test them as part of the distro. But the Path repository should not be in the `composer.json` in Git for all the reasons @gossi has mentioned in his blog post about this project and lot of comments. 

That is the point where this package comes into play as it helps defining the path repository outside of the code/files maintained by Git and keeping the repos clean. But I'm not 100% happy with the exact implementation he chose and will suggest a better approach in #3.
